version: '3.8'

services:
  app:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: watchstore
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # Mount thư mục db vào thư mục của MySQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
